### ISSUE TITLE
Questions regarding BCD events in CP state machine and state D in CP state machine.

### ISSUE THREAD

**Issue by Mohamed-Sedeek** [PionixPublic/yeti-firmware#3]
Dear Cornelius,
It's me again, I contacted you almost a month ago regarding something that I didn't fully understand about the Output Compare Mode in (ControlPilot), and your reply was very helpful, so thank you for that. I'm writing this email to inquire about two things. Firstly, the two events (EnterBCD) and (LeaveBCD) you're using in (runStateMachine) API in the (ControlPilot) module. What does BCD mean and what are those two events used for as I couldn't find any place in the code where you used them to take an action or change some variable? Secondly, in state D (Charging with ventilation) I don't see any action taken to actually turn ventilation on, so is this something that is done by hardware for example or is not even related to the EVSE but rather something the EV itself turns on?
Best regards
Mohamed Sedeek

**Comment by corneliusclaussen** [comment]
Hi Mohamed,

EnterBCD any state to state B / C  or D transition (and leave BCD the other way round). They are the events that trigger SLAC to start or stop. But please note we have a refactoring ongoing for the board support interface, see https://github.com/EVerest/everest-core/pull/379

Once this is merged the MCUs will no longer use these events, they will simply expose A/B/C/D/E/F states and the rest will be handled in EVerest itself. We will update the yeti-firmware to this new interface soon as well.

Regarding ventilation: State D indicates the EV wants to charge but only if ventilation is available. This was introduced when lead-acid batteries were used, those should not be charged inside (as hydrogen gas may be released during charging) unless there is some sort of ventilation. So it is more of a config setting in the charger, i.e. is this charger located outdoors or has sufficient fresh air ventilation. 

It is not used nowadays anymore with lithium batteries though, so it is merely included for completeness. Many commercial chargers do not support this anymore and that is ok.

Best

Cornelius

**Comment by caller** [comment]
closed since no follow up and questions sees to be anwered
